fix: Release Check workflow

diff --git a/.github/workflows/release_check.yml b/.github/workflows/release_check.yml
--- a/.github/workflows/release_check.yml
+++ b/.github/workflows/release_check.yml
@@ -18,14 +18,14 @@ jobs:
         uses: actions/setup-node@v3.6.0
         with:
           node-version-file: ".nvmrc"
-      - name: Get latest version
+      - name: Get the latest version
         id: latest_version
         run: |
           latest_tag=$(git describe --tags --abbrev=0)
           latest_version=$(echo $latest_tag | sed 's/v//')
           echo "Latest version: $latest_version"
           echo "::set-output name=latest_version::$latest_version"
-      - name: Get proposed version
+      - name: Get the proposed version
         id: proposed_version
         run: |
           proposed_version=$(node -p "require('./package-lock.json').version")
@@ -37,10 +37,10 @@ jobs:
           proposed_version: ${{ steps.proposed_version.outputs.proposed_version }}
         run: |
           echo npx semver -r ">$latest_version" "$proposed_version"
-          npx semver -r ">$latest_version" "$proposed_version"
+          npx semver -r ">$latest_version" "$proposed_version" > /dev/null && echo "Proposed version is valid" || (echo "Proposed version is invalid" && exit 1)
       - name: Check change log
         env:
           proposed_version: ${{ steps.proposed_version.outputs.proposed_version }}
         run: |
           proposed_version_for_regex=$(echo $proposed_version | sed 's/\./\\\\./g')
-          grep -E '## \[$proposed_version_for_regex\] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' CHANGELOG.md
+          grep -E '## \[$proposed_version_for_regex\] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
