add: workflow for gh releases

diff --git a/.github/workflows/release_check.yml b/.github/workflows/release_check.yml
--- a/.github/workflows/release_check.yml
+++ b/.github/workflows/release_check.yml
@@ -19,26 +19,26 @@ jobs:
         with:
           node-version-file: ".nvmrc"
       - name: Get the latest version
-        id: latest_version
+        id: get_latest_version
         run: |
           latest_tag=$(git describe --tags --abbrev=0)
           latest_version=$(echo $latest_tag | sed "s/v//")
           echo "latest_version=$latest_version" >> "$GITHUB_OUTPUT"
           echo "Latest version: $latest_version"
       - name: Get the proposed version
-        id: proposed_version
+        id: get_proposed_version
         run: |
           proposed_version=$(node -p "require('./package-lock.json').version")
           echo "proposed_version=$proposed_version" >> "$GITHUB_OUTPUT"
           echo "Proposed version: $proposed_version"
       - name: Check version
         env:
-          latest_version: ${{ steps.latest_version.outputs.latest_version }}
-          proposed_version: ${{ steps.proposed_version.outputs.proposed_version }}
+          latest_version: ${{ steps.get_latest_version.outputs.latest_version }}
+          proposed_version: ${{ steps.get_proposed_version.outputs.proposed_version }}
         run: npx semver -r ">$latest_version" "$proposed_version" > /dev/null && echo "Proposed version is valid" || (echo "Proposed version is invalid" && exit 1)
       - name: Check change log
         env:
-          proposed_version: ${{ steps.proposed_version.outputs.proposed_version }}
+          proposed_version: ${{ steps.get_proposed_version.outputs.proposed_version }}
         run: |
           proposed_version_for_regex=$(echo $proposed_version | sed "s/\./\\\\./g")
-          grep -E "## \[$proposed_version_for_regex\] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}" CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
+          grep -P "## \[$proposed_version_for_regex\] - \d{4}-\d{2}-\d{2}" CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
