fix: Release Check workflow

diff --git a/.github/workflows/release_check.yml b/.github/workflows/release_check.yml
--- a/.github/workflows/release_check.yml
+++ b/.github/workflows/release_check.yml
@@ -22,15 +22,15 @@ jobs:
         id: latest_version
         run: |
           latest_tag=$(git describe --tags --abbrev=0)
-          latest_version=$(echo $latest_tag | sed 's/v//')
+          latest_version=$(echo $latest_tag | sed "s/v//")
           echo "Latest version: $latest_version"
-          echo "latest_version=$latest_version >> $GITHUB_OUTPUT"
+          echo "latest_version=$latest_version" >> "$GITHUB_OUTPUT"
       - name: Get the proposed version
         id: proposed_version
         run: |
           proposed_version=$(node -p "require('./package-lock.json').version")
           echo "Proposed version: $proposed_version"
-          echo "proposed_version=$proposed_version >> $GITHUB_OUTPUT"
+          echo "proposed_version=$proposed_version" >> "$GITHUB_OUTPUT"
       - name: Check version
         env:
           latest_version: ${{ steps.latest_version.outputs.latest_version }}
@@ -42,5 +42,5 @@ jobs:
         env:
           proposed_version: ${{ steps.proposed_version.outputs.proposed_version }}
         run: |
-          proposed_version_for_regex=$(echo $proposed_version | sed 's/\./\\\\./g')
-          grep -E '## \[$proposed_version_for_regex\] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}' CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
+          proposed_version_for_regex=$(echo $proposed_version | sed "s/\./\\\\./g")
+          grep -E "## \[$proposed_version_for_regex\] - [[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}" CHANGELOG.md > /dev/null && echo "Change log is valid" || (echo "Change log is invalid" && exit 1)
